### Recuperar información del pokemon ditto
GET http://localhost:3003/pokemon/ditto

### Para crear un Pokemon
POST http://localhost:3003/pokemon
Content-Type: application/json

{
  "name": "ditto",
  "type": "normal",
  "moves": [
      "transform"
  ]
}

